### ISSUE TITLE
Anticheat  .c_str() fix build debian 11

### ISSUE THREAD

**Issue by DykeRz** [TrinityCore/TrinityCoreCustomChanges#132]
**Description

**Current behavio

**Expected behaviour:**

Passive anticheat fix linux, need to add some .c_str() like this to:

sWorld->SendGMText(LANG_ANTICHEAT_COUNTERMEASURE, str.c_str(), player->GetName().c_str(), player->GetName().c_str());

**Steps to reproduce the problem:**

Apply anticheat to last TC

Try to compile in deb11

You will get errors:
/home/server/TC/src/server/game/Anticheat/AnticheatMgr.cpp:315:63: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic method; call will abort at runtime [-Wnon-pod-varargs]
            sWorld->SendGMText(LANG_ANTICHEAT_COUNTERMEASURE, str, player->GetName(), player->GetName());sWorld->SendGMText(LANG_ANTICHEAT_COUNTERMEASURE, str, player->GetName(), player->GetName());

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3194345
(Deb64, Debug, Static)

**TDB version:** 

TDB 335.24011

**Operating system:** debian 11

**Comment by acidmanifesto** [comment]
The c_str() was removed due to the fmt changes incorporated with main tc.
Please update your main tc 3.3.5 branch.

PR related to the fmt changes https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/110

Update: i am being told of a c_str() being required by someone else just now. So something must of changed since i been would of the country for a month, just came back yesterday. I will look it over this week and make any corrections with the current build

**Comment by DykeRz** [comment]
> The c_str() was removed due to the fmt changes incorporated with main tc. Please update your main tc 3.3.5 branch.
> 
> PR related to the fmt changes #110
> 
> Update: i am being told of a c_str() being required by someone else just now. So something must of changed since i been would of the country for a month, just came back yesterday. I will look it over this week and make any corrections with the current build

yes, we need c_str now for anticheat
