### ISSUE TITLE
add to passive anticheat one way to notify player accounts of gms to see hacks being used notifications

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCoreCustomChanges#3]
my idea for easy maintenance is to use a new table on auth database where you fill the player accounts of gms.

**Comment by Baynar** [comment]
Something as "[Player] Name: Using Wall Climb Hack!" and its also saved to the database with datetime and everything ?

**Comment by Aokromes** [comment]
that text is already send on center of screen, my idea is to send it also on chat log.

**Comment by Baynar** [comment]
EDIT:
After
WorldPacket data(SMSG_NOTIFICATION, (str.size()+1));
data << str;
sWorld->SendGlobalGMMessage(&data);
Add:
WorldPacket data2(SMSG_SERVER_MESSAGE, (str.size()+1));
data2 << str;
sWorld->SendGlobalGMMessage(&data2);

in
void AnticheatMgr::BuildReport(Player* player,uint8 reportType)

This will send message to both center of the screen and chat box for gm's so if you are afk for a few minutes you can scroll up your chat or check database for dem hackers.

**Comment by Baynar** [comment]
Can you explain your current idea in more detail ?
I cannot understand what you mean by "fill the player accounts of gms".

**Comment by Aokromes** [comment]
you have gm accounts 1,  2, 3 you have  player accounts 4,5,6 player on account 7 hacks, and gm is online with account 4, he gets warning because he is player account of gm account 1.

**Comment by Baynar** [comment]
I looked up how Trinity handles the packet and it seems you can do it from database.
One way to do it add the player account in RBAC.
2nd way same as first way but make a new RBAC permission list with player command + sendglobalgmtext

The worst way to do it would be to mod core to check if player has a linked gm account but that is not the best way to handle it since TrinityCore has RBAC.

Best way to do it from my point of view is to Create a new RBAC table with linked accounts that you load with the other tables and then when setting RBAC_PERM_RECEIVE_GLOBAL_GM_TEXTMESSAGE make sure to also get the accounts from RBAC_linked_accounts

**Comment by acidmanifesto** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/73

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/d534d6ed0a2f883bff049f3ab28e9c47175a3307
